[package]
name = "RustLSystem"
version = "0.1.0"
authors = ["DevWillAtkinson <williamlandonatkinson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtle = "1.0.0-rc.3"